# Generated by Django 4.2.9 on 2024-01-07 11:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('Entertainment', 'Entertainment'), ('Food', 'Food'), ('Education', 'Education'), ('Sports', 'Sports')], max_length=120, null=True)),
                ('image', models.ImageField(null=True, upload_to='uploads/')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
